# Generated by Django 3.2.2 on 2021-05-14 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_images'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Todos',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
