# Generated by Django 3.2.2 on 2021-05-16 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210516_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='sender_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender_id', to='user.users'),
        ),
        migrations.AlterField(
            model_name='messages',
            name='two_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.users'),
        ),
    ]
