# Generated by Django 3.2.2 on 2021-05-16 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210516_0847'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
