# Generated by Django 3.2.2 on 2021-05-16 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_delete_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Messages',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
