# Generated by Django 3.2.2 on 2021-05-20 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0008_auto_20210516_1954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('img', models.CharField(max_length=25)),
                ('content', models.TextField()),
            ],
        ),
    ]
