# Generated by Django 3.2.2 on 2021-05-21 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todos',
            name='img',
        ),
    ]
