# Generated by Django 3.2.2 on 2021-05-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_todos_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='todos',
            name='viewers',
            field=models.IntegerField(default=0),
        ),
    ]
