# Generated by Django 3.2.2 on 2021-05-24 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_posts_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='img',
        ),
    ]
