# Generated by Django 3.2.2 on 2021-05-26 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='post_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='post_id', to='blog.posts'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
