# Generated by Django 3.2.2 on 2021-05-24 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='')),
                ('title', models.CharField(blank=True, max_length=25)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
